server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?useunicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mapper:
  mappers:
    - tk.mybatis.mapper.common.Mapper

  not-empty: true

logging:
  level:
     com.alex.spring.boot.blog.mapper: debug
mybatis:
  mapper-locations: classpath:mapper/*.xml
  base-packages: com.alex.spring.boot.blog.mapper
  configuration:
    map-underscore-to-camel-case: true #驼峰转下划线配置

#pagehelper.helperDialect=com.github.pagehelper.dialect.helper.MySqlDialect
#pagehelper.reasonable=true
#pagehelper.supportMethodsArguments=true
#pagehelper.params=count=countSql
pagehelper:
  helper-dialect: com.github.pagehelper.dialect.helper.MySqlDialect
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
### jwt
jwt:
  ###过期时间 s数432000 5天
  time: 432000
  ###安全密钥
  secret: "BlogSecret"
  ###token前缀
  prefix: "Bearer "
  ###http头key
  header: "Authorization"

